baseURL = "https://shogo82148.github.io/"
languageCode = "ja-jp"
title = "Shogo's Blog"
theme = "hugo-octopress"

pygmentsUseClasses = true
pygmentsCodeFences = true

[permalinks]
  post = "/blog/:year/:month/:day/:slug/"

[params]
  author = "ICHINOSE Shogo"
  subtitle = ""
  googleAnalytics = "UA-4526627-4"
  searchEngineURL = "https://www.google.com/search"
  github = "https://github.com/shogo82148/"
  twitter = "https://twitter.com/shogo82148/"
  sidebarRecentLimit = 10
  customcss = ["css/syntax.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
