version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.1
    steps:
      - restore_cache:
          keys:
            - go1.10.1-hugo-{{ .Revision }}
            - go1.10.1-hugo
      - checkout
      - run: go get -u go get -v github.com/spf13/hugo
      - run: hugo
      - save_cache:
          key: go1.10.1-hugo-{{ .Revision }}
          paths:
            - /go/bin/hugo
            - /go/src/github.com
